# -*- coding: utf-8 -*-
"""Image_Classification_AISE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0BsZkGjN4jlkG_VKF0GV_gLPe83MmSx
"""

from google.colab import drive
drive.mount('/content/drive')

"""# AISE Project Experiment
**Task**: wildfire image classification

**Objective**: This project aims to analyze and record the factors influencing energy consumption(carbon footrpint) during the training of image classification model in a Google Colab environment. By focusing on key variables, we can identifying following factors:
1. controllable variables
2. constant
3. target
4. sustainable indicators

**Stage**:

(1) Data Import
(2) Data Preprocessing
(3) Training

**Measurement**:

- Resource Usage(CPU, GPU, RAM)
- Time
- Electricity Consumption(estimated)

**Scope**:
1. hardware resources
- cpu vs gpu
2. Model complexity
- parameter count
- layer depth and structure
3. Dataset Characteristics
- Dataset size
- Data Preprocessing
4. Training Configuration
- Batch size
- Number of epochs
"""

import os
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D, Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
import time
from tqdm import tqdm

# ✅ [1] DATA IMPORT: 이미지 폴더에서 numpy 배열로 로딩
def load_images_from_folder(folder, label):
    images, labels = [], []
    for filename in tqdm(os.listdir(folder), desc=f"Loading {os.path.basename(folder)}"):
        img_path = os.path.join(folder, filename)
        try:
            img = Image.open(img_path).resize((224, 224)).convert("RGB")
            images.append(np.array(img) / 255.0)  # 정규화 포함
            labels.append(label)
        except:
            continue  # 손상된 이미지 건너뛰기
    return images, labels

fire_imgs, fire_labels = load_images_from_folder('/content/drive/MyDrive/AI for the sustainable environment (AISE) project/Image_Classification/wildfire/train/wildfire', 1)
nofire_imgs, nofire_labels = load_images_from_folder('/content/drive/MyDrive/AI for the sustainable environment (AISE) project/Image_Classification/wildfire/test/wildfire', 0)

X = np.array(fire_imgs + nofire_imgs)
y = np.array(fire_labels + nofire_labels)

# ✅ [2] DATA PREPROCESSING: 학습/검증 분할
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# ✅ [3] MODEL TRAINING: Custom CNN 정의 및 학습
def build_custom_cnn(input_shape, depth):
    model = Sequential()
    filters = 32
    for i in range(depth):
        if i == 0:
            model.add(Conv2D(filters, (3, 3), activation='relu', padding='same', input_shape=input_shape))
        else:
            model.add(Conv2D(filters, (3, 3), activation='relu', padding='same'))
        model.add(BatchNormalization())
        model.add(MaxPooling2D(pool_size=(2, 2)))
        filters *= 2
    model.add(GlobalAveragePooling2D())
    model.add(Dense(128, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(1, activation='sigmoid'))
    return model

depth = 2
batch_size = 64
epochs = 10
input_shape = (224, 224, 3)

model = build_custom_cnn(input_shape, depth)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

start_time = time.time()
history = model.fit(
    X_train, y_train,
    validation_data=(X_valid, y_valid),
    epochs=epochs,
    batch_size=batch_size,
    callbacks=[early_stop],
    verbose=1
)
end_time = time.time()
training_duration = round(end_time - start_time, 2)

# ✅ 결과 요약
{
    "depth": depth,
    "batch_size": batch_size,
    "epochs_requested": epochs,
    "epochs_run": len(history.history['loss']),
    "param_count": model.count_params(),
    "training_time_sec": training_duration
}